exp_base: ckpt/llff/trex_softplus
random_seed: 0

# Logging
wandb:
  project: nerf_llff_trex
  name: shifted_softplus

# Data
dataset_type: llff
data_root: /home/ziyang/Desktop/Datasets/nerf_dataset/nerf_llff_data/trex
#data_root: /media/SSD/ziyang/Datasets/nerf_dataset/nerf_llff_data/trex
factor: 8
hold_for_test: 8

# Fourier embedding
n_freq_point: 10
n_freq_view: 4

# MLP
n_layer: 8
n_dim: 256
use_viewdir: True
rgb_act: sigmoid
density_act: relu

two_model_for_fine: True
train_on_coarse: True

# Ray & point sampling
use_batching: True
use_ndc: True
n_sample_ray: 1024
n_sample_point: 64
n_sample_point_fine: 64
perturb: True
density_noise_std: 1.0

# Rendering
no_batching: True
white_bkgd: False

# Training
n_iters: 200000
lrate: 0.0005
lrate_decay: 0.1
lrate_decay_step: 500000

val_freq: 500
save_freq: 1000

chunk_ray: 4096
chunk_point: 4096*256
half_res: True