exp_base: ckpt/blender/lego_softplus
random_seed: 0

# Logging
wandb:
  project: nerf_blender_lego
  name: shifted_softplus

# Data
dataset_type: blender
#data_root: /home/ziyang/Desktop/Datasets/nerf_dataset/nerf_synthetic/lego
data_root: /media/SSD/ziyang/Datasets/nerf_dataset/nerf_synthetic/lego

# Fourier embedding
n_freq_point: 10
n_freq_view: 4

# MLP
n_layer: 8
n_dim: 256
use_viewdir: True
rgb_act: sigmoid
density_act: shifted_softplus

two_model_for_fine: True
train_on_coarse: True

# Ray & point sampling
use_batching: False
use_ndc: False
n_sample_ray: 1024
n_sample_point: 64
n_sample_point_fine: 128
perturb: True
density_noise_std: 0.0

# Rendering
no_batching: True
white_bkgd: True

# Training
n_iters: 200000
lrate: 0.0005
lrate_decay: 0.1
lrate_decay_step: 500000

precrop_iters: 500
precrop_frac: 0.5

val_freq: 500
save_freq: 1000

chunk_ray: 4096
chunk_point: 1000000
half_res: True